[package]
name = "AptoSpaceNFT"
version = "0.1.0"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'testnet'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.AptosToken]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'testnet'
subdir = 'aptos-move/framework/aptos-token'

[addresses]
aptos_framework = "0x1"
source_addr = "_"
aptospace_nft = "_"
